### ISSUE TITLE
gcov detection fails on Windows if version is found at end of line

### ISSUE THREAD

**Issue by mitchgrout** [mozilla/grcov#1189] opened 2024-07-15 00:04 UTC
[gcov::parse_version](https://github.com/mozilla/grcov/blob/cc77ce34164fc3ea80ac579d1c15f36c9734133c/src/gcov.rs#L99) currently splits words using either whitepace or newlines, but does not account for carriage returns. This can lead to failures to detect valid `gcov` binaries on Windows. Example using the [`w64devkit`](https://github.com/skeeto/w64devkit) bundled version of `gcov`:

```bash
$ gcov --version | head -n1
gcov (GCC) 14.1.0

$ gcov --version | head -n1 | xxd -c20
00000000: 6763 6f76 2028 4743 4329 2031 342e 312e 300d 0a    gcov (GCC) 14.1.0..
```

The gathered `versions` are `["gcov", "(GCC)", "14.1.0<CR>"]`, all of which fail `Version::parse`

This could be fixed by adding `'\r'` into this list, or by using `char.is_whitespace` or `char.is_ascii_whitespace`

**Comment by feo-elektronik-may** [comment] 2024-07-24 08:36
This is a duplicate of #919, and a fix is already available in #1179.
I chose to trim away all whitespace in version number candidates instead of adding any special logic for `\r` or modifying the splitting logic.

Unfortunately, it seems like this project is not getting maintained right now, so the PR has been open for 3 months without any feedback already.

**Closed** 2024-09-24 18:24 UTC
