### ISSUE TITLE
Rust struct lines are counted as "missing"

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/grcov#450] opened 2020-06-06 04:15 UTC
We started using github actions with grcov for ICU4X and we struggle with a high number of lines that are marked as not covered.

Example: https://coveralls.io/builds/31270593/source?filename=components/locale/src/locale.rs

In this file the first line of the file is marked as uncovered and the struct is marked as such as well accounting for all 7 uncovered lines.
Same thing applies to basically all other files in our project.

Is it a known bug?

**Comment by calixteman** [comment] 2020-06-06 10:07
I can't see the source code with the above link.

**Comment by zbraniecki** [comment] 2020-06-06 10:17
Agh, weird. It does show `source not available` when you're not logged in. I reported it in https://github.com/lemurheavy/coveralls-public/issues/1456

Here's a screenshot:

![Screenshot_2020-06-06 Coveralls io - Test Coverage History and Statistics](https://user-images.githubusercontent.com/449986/83941955-45751e80-a7a4-11ea-9ae8-0535a1a2dfdd.png)

**Comment by calixteman** [comment] 2020-06-06 11:01
The problem is that some code is added for Debug stuff (because of `derive(Debug)`) and the debug info for this extra code come from the struct definition itself.
So on the llvm's side there are some block associated with lines coming from the struct definition.
You can see that in generating llvm ir or in inspecting dwarf from the debug binary.
So it appears that in your tests you never call Locale::default() or never compare Locale or never debug-print a Locale, ...
A way to fix that is to have a test which uses one of the trait you've in derive.
You could say: "it's useless to test Debug" and I'd agree but if you have something like `derive(FooBar)` and you implemented FooBar stuff maybe it's worth having test for it.
So I'm not sure that's really a bug.
Sometimes it's useful to just have `derive(Debug)` for debug purpose and you don't want to add test for that (who wants to do that...) so in this case you could pre-process your code before compiling it for ccov using sed to comment/remove this kind of thing to avoid to see uncovered lines.

**Comment by marco-c** [comment] 2020-06-12 10:03
> you could pre-process your code before compiling it for ccov using sed to comment/remove this kind of thing to avoid to see uncovered lines

Another option could be to use the feature added in https://github.com/mozilla/grcov/pull/416#issuecomment-612562052 (perhaps we should add an example to the README).

**Comment by marco-c** [comment] 2020-11-03 11:54
This is older than #476, but that one has more details and a possible workaround, so I'll mark this as duplicate of #476.

**Closed by marco-c** 2020-11-03 11:54 UTC

**Comment by ekoutanov** [comment] 2022-08-13 06:52
I've also encountered the case where the first line of a module appears to be uncovered — that line happens to be a doc comment. Every other line in the file appears to be covered.

As a workaround, I've added `--excl-line "(//!|///)"` to `grcov`.
