### ISSUE TITLE
Failed to create a symlink of profraw on nightly-msvc

### ISSUE THREAD

**Issue by tcztzy** [mozilla/grcov#561] opened 2021-01-12 08:07 UTC
I followed the manual from README, both `.profraw` and `.gcda`. And then I try to run following command to generate coverage report have the same panic

```
grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/
07:44:41 [ERROR] A panic occurred grcov-0.6.1\src\producer.rs:296: Failed to create a symlink "${workspace}\\default.profraw" -> "${tmpdir}\\default_1.profraw"
```

I also read [this issure](https://github.com/mozilla/grcov/issues/462), but I need some Windows specified dependecies so I do pin `nightly-msvc`.

Is there any walkaround for this problem?

**Comment by marco-c** [comment] 2021-01-21 18:15
Are both source-based coverage and gcov-based coverage failing?

Before running `cargo test`, can you make sure you remove all *.profraw and *.gcda files that are in your source tree?

1. Remove all profraw and gcda files
2. `cargo build`
3. `cargo test`
4. Run `grcov`

If it still fails, can you try running `grcov PATHTOPROFRAW1 PATHTOPROFRAW2 ... -s . ` instead of `grcov . -s .`?

**Comment by lolo32** [comment] 2021-03-21 22:07
I got the same problem, and I just tried what you asked: remove, guild, test, grcov

I found a temporary solution:

> Open the CMD with Administrator right

**Comment by marco-c** [comment] 2021-11-25 18:57
Duplicate of #462.

**Comment by marco-c** [comment] 2021-11-25 18:57
#720 should fix this.

**Closed by marco-c** 2021-11-25 18:57 UTC
Labels: bug
