### ISSUE TITLE
Question: Why does coverage include test code?

### ISSUE THREAD

**Issue by wllenyj** [mozilla/grcov#779] opened 2022-02-16 11:11 UTC
Maybe this shouldn't be mentioned here, but I'm really confused.
Why does coverage include test code？Is this normal behavior? Did I do something wrong?

![image](https://user-images.githubusercontent.com/8768126/154252658-1a8eb1d1-33e9-42a2-8658-b42dfab66a67.png)

My ci system is here: https://github.com/openanolis/dragonball-sandbox/pull/42

Thanks.

**Comment by marco-c** [comment] 2022-02-16 11:29
Duplicate of #728.

**Closed by marco-c** 2022-02-16 11:29 UTC
Labels: duplicate

**Comment by wllenyj** [comment] 2022-02-16 13:33
> #728

Thanks for your replay.

**Comment by wllenyj** [comment] 2022-02-16 15:44
Hi, @marco-c.
Sorry to bother you, I want to ask a question.
In the pr I mentioned above, the coverage has dropped a lot, after comparing the previous lcov file:
previous lcov: [code](https://app.codecov.io/gh/openanolis/dragonball-sandbox/blob/3beca02a39e9fffc6eba7d06567f8aac399821ae/crates/db-arch/src/x86_64/cpuid/mod.rs)
```
SF:crates/db-arch/src/x86_64/cpuid/mod.rs
FN:50,db_arch::x86_64::cpuid::process_cpuid
FN:69,db_arch::x86_64::cpuid::tests::test_invalid_cpuid
FN:50,db_arch::x86_64::cpuid::process_cpuid
FN:69,db_arch::x86_64::cpuid::tests::test_invalid_cpuid::{{closure}}
FNDA:1,db_arch::x86_64::cpuid::process_cpuid
FNDA:1,db_arch::x86_64::cpuid::tests::test_invalid_cpuid
FNDA:0,db_arch::x86_64::cpuid::process_cpuid
FNDA:1,db_arch::x86_64::cpuid::tests::test_invalid_cpuid::{{closure}}
FNF:4
FNH:3
BRF:0
BRH:0
DA:50,2
DA:51,2
DA:54,1
DA:58,0
DA:60,1
DA:62,2
DA:69,2
DA:70,1
DA:71,1
DA:73,1
DA:74,2
LF:11
LH:10
end_of_record
```
lcov file of my pr, [code](https://app.codecov.io/gh/openanolis/dragonball-sandbox/blob/655a50d10f99c5561c69a43e6c49caaceba40da7/crates/db-arch/src/x86_64/cpuid/mod.rs)
```
SF:crates/db-arch/src/x86_64/cpuid/mod.rs
FN:65,db_arch::x86_64::cpuid::tests::test_invalid_cpuid::{{closure}}
FN:46,db_arch::x86_64::cpuid::process_cpuid
FN:46,db_arch::x86_64::cpuid::process_cpuid
FN:65,db_arch::x86_64::cpuid::tests::test_invalid_cpuid
FNDA:1,db_arch::x86_64::cpuid::tests::test_invalid_cpuid::{{closure}}
FNDA:1,db_arch::x86_64::cpuid::process_cpuid
FNDA:0,db_arch::x86_64::cpuid::process_cpuid
FNDA:1,db_arch::x86_64::cpuid::tests::test_invalid_cpuid
FNF:4
FNH:3
BRDA:49,0,0,1
BRDA:49,0,1,1
BRDA:49,0,2,-
BRDA:49,0,3,-
BRDA:49,0,4,1
BRDA:49,0,5,-
BRDA:49,0,6,-
BRDA:49,0,7,-
BRDA:49,0,8,-
BRDA:49,0,9,-
BRDA:49,0,10,-
BRDA:49,0,11,-
BRDA:49,0,12,-
BRDA:49,0,13,-
BRDA:49,0,14,-
BRDA:49,0,15,-
BRDA:49,0,16,-
BRDA:49,0,17,-
BRDA:49,0,18,-
BRDA:49,0,19,-
BRDA:49,0,20,-
BRDA:49,0,21,-
BRDA:49,0,22,-
BRDA:49,0,23,-
BRDA:49,0,24,-
BRDA:49,0,25,-
BRDA:49,0,26,-
BRDA:49,0,27,-
BRDA:49,0,28,1
BRDA:49,0,29,-
BRDA:49,0,30,1
BRDA:49,0,31,-
BRDA:49,0,32,1
BRDA:49,0,33,-
BRDA:49,0,34,1
BRDA:49,0,35,-
BRDA:49,0,36,1
BRDA:49,0,37,-
BRDA:49,0,38,1
BRDA:49,0,39,-
BRDA:49,0,40,1
BRDA:49,0,41,-
BRDA:49,0,42,1
BRDA:49,0,43,-
BRDA:49,0,44,1
BRDA:49,0,45,-
BRDA:49,0,46,1
BRF:47
BRH:13
DA:46,2
DA:49,2
DA:51,1
DA:54,0
DA:56,1
DA:58,2
DA:65,2
DA:66,1
DA:67,1
DA:69,1
DA:70,2
LF:11
LH:10
end_of_record
```
which has a lot more information about branches.
For easy viewing, I paste the source code here.
``` Rust
pub fn process_cpuid(kvm_cpuid: &mut CpuId, vm_spec: &VmSpec) -> Result<(), Error> {
    use transformer::CpuidTransformer;

    match vm_spec.cpu_vendor_id() {
        self::common::VENDOR_ID_INTEL => {
            self::transformer::intel::IntelCpuidTransformer::new().process_cpuid(kvm_cpuid, vm_spec)
        }
        self::common::VENDOR_ID_AMD => {
            self::transformer::amd::AmdCpuidTransformer::new().process_cpuid(kvm_cpuid, vm_spec)
        }
        _ => Err(Error::CpuNotSupported),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_invalid_cpuid() {
        let mut cpuid = CpuId::new(0).unwrap();
        let vm_spec = VmSpec::new(0, 2, 1, 1, 1, VpmuFeatureLevel::Disabled).unwrap();

        process_cpuid(&mut cpuid, &vm_spec).unwrap();
    }
}
```

**Comment by marco-c** [comment] 2022-02-28 19:06
What exactly did you change in the PR? It's weird that there was no branch information before and there is branch information after.

**Comment by wllenyj** [comment] 2022-03-04 07:20
@marco-c Thank you.

It is indeed caused by branch information, and branch information will reduce coverage.

I changed `branches` to false, same as before.

https://github.com/openanolis/dragonball-sandbox/blob/fc72d090e14776dcf9cc27f7ee9b45e7517d1faf/.github/grcov.yml#L1
