### ISSUE TITLE
Broken on GCC 8

### ISSUE THREAD

**Issue by zhihaoy** [mozilla/grcov#389] opened 2020-02-19 20:42 UTC
```
20:40:39 [ERROR] Error parsing file build: Record containing invalid integer: 'lcount:35,0,1'
20:40:39 [ERROR] Error parsing file build: Record containing invalid integer: 'lcount:17,2,0'
```

**Comment by marco-c** [comment] 2020-02-19 20:44
Duplicate of #55.
The format has changed in GCC 8 (and again in GCC 9). We'll need to add support for parsing it.

**Closed by marco-c** 2020-02-19 20:44 UTC
Labels: duplicate
