### ISSUE TITLE
Unexpected uncovered line

### ISSUE THREAD

**Issue by allevo** [mozilla/grcov#434] opened 2020-05-07 22:21 UTC
Hi!
I'm trying to create a coverage report for my project. This crate works well: it's amazing! thanks!

Anyway there're some unexpected behaviour for some rows.
The following lines are my `main.rs`
```rust

#[cfg_attr(test, derive(Clone))]
pub struct Printer {
    pub say: String,
}

impl Printer {
    pub fn format(&self, name: Option<String>) -> String {
        let name: String = match name {
            None => "World".to_owned(),
            Some(name) => name,
        };
        format!("{} {}!", self.say, name)
    }
}

fn main() {
    let printer = Printer { say: "Hello".to_owned() };
    let s = printer.format(Some("tom".to_owned()));
    println!("{}", s);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_should_set_say_member() {
        let printer = Printer { say: "Hello".to_owned() };
        assert_eq!(printer.say, "Hello".to_owned());
    }
    #[test]
    fn test_format_should_return_the_right_string() {
        let printer = Printer { say: "Hello".to_owned() };
        let result = printer.format(Some("Tom".to_owned()));
        assert_eq!(result, "Hello Tom!".to_owned());
    }
    #[test]
    fn test_format_should_fallback_on_none() {
        let printer = Printer { say: "Hello".to_owned() };
        let result = printer.format(None);
        assert_eq!(result, "Hello World!".to_owned());
    }
}
```

From my point of view, all lines are covered except `main` function. But the coverage report considers those two lines as uncovered
![image](https://user-images.githubusercontent.com/1054125/81350116-90c2e100-90c1-11ea-9d0b-8d2554a4158a.png)

Those are the commands I run:
```bash
rm -rf target
cargo +nightly build
cargo +nightly test
grcov ./target/debug/ -s . -t html --llvm --branch --ignore-not-existing -o ./target/debug/coverage/
open target/debug/coverage/index.html
```
 
Why that lines are considered uncovered?

**Comment by calixteman** [comment] 2020-05-08 10:54
Because of `#[cfg_attr(test, derive(Clone))]`.
In fact it adds some code associated with the two lines (I mean debug info for the added code corresponds to above lines).

**Comment by allevo** [comment] 2020-05-08 11:21
Hi! thanks the the reply.
I don't understand:
- my code should run as `test` as target, so the `cfg_attr` should be "true" (tests clone the `Printer` struct)
- the `say` property is used in the test and in the code

**Comment by HuangSSShihua** [comment] 2020-05-12 13:26
> Because of `#[cfg_attr(test, derive(Clone))]`.
> In fact it adds some code associated with the two lines (I mean debug info for the added code corresponds to above lines).

I am currently facing the same issue. In the codecov report, a 200+ line code gives 110+ functions and 150+ branches...... and yes I have checked those unexpected functions and branches coming from the attributes. 
So is it possible to skip those attributes when generating reports?

**Comment by calixteman** [comment] 2020-05-12 14:20
You can remove `-Clink-dead-code` from rustc flags.
This option can help to detect dead code but I'd say that the compiler is able to detect (and emit a warning) unused functions in almost all the cases.
So please give it a try and give some feedback here.

**Comment by HuangSSShihua** [comment] 2020-05-13 11:05
This is the result with `-Clink-dead-code`
![image](https://user-images.githubusercontent.com/33181613/81802565-a186b300-9516-11ea-9284-29eda1f88ff5.png)
This is the result without `-Clink-dead-code`
![image](https://user-images.githubusercontent.com/33181613/81802716-ddba1380-9516-11ea-8f56-d20a07953b1c.png)
But yes some attributes like `Debug` is still counted.

Besides, Im not sure what is the proper way to get test coverage for a crate. 
To test the crate I created, in the integration test the functions from the crate are called to verify their functionalities. For instance `FunctionA` is called and returns `StructB`. Then in the integration test, the 'StructB' is deserialized. However, the test result shows the Deserialize attribute is not hit.

Is possible to cover the function called in the integration test?

**Comment by marco-c** [comment] 2020-11-24 10:50
I know this is older than #476, but that one has more details and a possible workaround, so I'll mark this as duplicate of #476.

BTW, you could try source-based coverage now, I've recently added support for it in grcov (version 0.6.0). Short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.

**Closed by marco-c** 2020-11-24 10:50 UTC
