### ISSUE TITLE
Add an option to keep files which are only in a dir

### ISSUE THREAD

**Issue by calixteman** [mozilla/grcov#178] opened 2018-10-03 16:19 UTC
We could implement options filter=regex and exclude=regex, to be able to keep the files we want.

**Comment by marco-c** [comment] 2018-10-04 08:40
The `exclude` is already implemented.

**Comment by calixteman** [comment] 2018-10-04 08:46
yes it is

**Comment by rdimartino** [comment] 2020-06-14 20:21
I think is a duplicate of #332

**Closed** 2020-06-17 00:03 UTC
Labels: duplicate, good-first-bug, rust
