### ISSUE TITLE
Unexpected uncovered lines

### ISSUE THREAD

**Issue by xxchan** [mozilla/grcov#467] opened 2020-07-12 02:43 UTC
https://coveralls.io/builds/32005412/source?filename=zircon-object/src/object/mod.rs
`RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Coverflow-checks=off'`

<img width="295" alt="1" src="https://user-images.githubusercontent.com/37948597/87237715-43018680-c42c-11ea-9a5b-2ae9ee4472ed.png">

<img width="455" alt="2" src="https://user-images.githubusercontent.com/37948597/87237716-45fc7700-c42c-11ea-80f1-764c8c47f343.png">

<img width="490" alt="3" src="https://user-images.githubusercontent.com/37948597/87237717-485ed100-c42c-11ea-9c85-b4b622c8f998.png">

**Comment by marco-c** [comment] 2020-11-24 10:48
You could try source-based coverage, I've recently added support for it in grcov (version 0.6.0). Short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.

**Comment by marco-c** [comment] 2020-11-24 10:49
I know this is older than #476, but that one has more details and a possible workaround, so I'll mark this as duplicate of #476.

**Closed by marco-c** 2020-11-24 10:49 UTC
